### ISSUE TITLE
Thank you x1000

### ISSUE THREAD

**Issue by dustymac** [oflahero/QuickBooksAppMVC5#2]
I'm teaching myself to code and doing my best to improve in my spare time (mostly a hobby).  I have felt like QBO examples and documentation are 1) hard to find 2) confusing when I do find them and 3) often do not go far enough to show someone like myself a solid working example.  Today I found your sample app "QuickBooksAppMVC5" and it's been the most helpful piece of QBO code I have come across, period.  The Intuit Developer website frankly confuses me.  But with the help of your app I am beginning to understand OAuth, OpenID, etc. much better.  Great readme notes.  Wonderful WORKING example app.   Can't say enough how much I appreciate you publishing this for folks like myself.

Best,
dm

**Comment by oflahero** [comment]
Hey, that's really kind of you to take the time to write. It means a lot to know that someone found it useful. I appreciate it!

I spent such an unnecessarily long time tying the various strands together that I thought it a shame if I didn't put them all together in a boilerplate app. OAuth 1 is so ancient now, it's hard to find any relevant information on it. Intuit finally got it together with OAuth2 in July last year, but I haven't done any updating to support that. It should simplify a lot of the DevDefined explicit code when a more modern provider can be pulled in. I don't know how long more they're going to support OAuth1a.

Best of luck with the coding anyway, and thanks again for the kind words.
